name: food_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  
  google_generative_ai: ^0.4.7
  flutter_ai_toolkit: ^0.9.2
  
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  intl: ^0.18.1
  image_picker: ^1.2.1
  
  geolocator: ^10.1.1
  geocoding: ^2.2.2
  
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/image.png
    - assets/products.json
    - assets/cooking_recipes.json